# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Candidates
description: > # this means to ignore newlines until "baseurl:"
  A crowdsourced list of electorate candidates for the Australian Federal
  Election of 2016.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://votingchoices.com" # the base hostname & protocol for your site
author:
  name: Pat Allan
  uri: http://freelancing-gods.com

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
